//
// Generated file, do not edit! Created by opp_msgtool 6.1 from ClientMsg.msg.
//

#ifndef __CLIENTMSG_M_H
#define __CLIENTMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class ClientMsg;
/**
 * Class generated from <tt>ClientMsg.msg:6</tt> by opp_msgtool.
 * <pre>
 * // Message class for client-to-client communication
 * message ClientMsg
 * {
 *     int sourceId;              // ID of the sending client
 *     int destId;                // ID of the destination client
 *     int taskId;                // Task identifier
 *     int subtaskId;             // Subtask identifier
 *     int hopCount = 0;          // Tracks the number of hops
 *     int result = 0;            // Result of a computation
 *     bool isResult = false;     // Indicates a result message
 *     bool isGossip = false;     // Indicates a gossip message
 *     string gossipContent;      // Content for gossip protocol
 *     int array[];               // Array data for computation
 * }
 * </pre>
 */
class ClientMsg : public ::omnetpp::cMessage
{
  protected:
    int sourceId = 0;
    int destId = 0;
    int taskId = 0;
    int subtaskId = 0;
    int hopCount = 0;
    int result = 0;
    bool isResult_ = false;
    bool isGossip_ = false;
    omnetpp::opp_string gossipContent;
    int *array = nullptr;
    size_t array_arraysize = 0;

  private:
    void copy(const ClientMsg& other);

  protected:
    bool operator==(const ClientMsg&) = delete;

  public:
    ClientMsg(const char *name=nullptr, short kind=0);
    ClientMsg(const ClientMsg& other);
    virtual ~ClientMsg();
    ClientMsg& operator=(const ClientMsg& other);
    virtual ClientMsg *dup() const override {return new ClientMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSourceId() const;
    virtual void setSourceId(int sourceId);

    virtual int getDestId() const;
    virtual void setDestId(int destId);

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);

    virtual int getSubtaskId() const;
    virtual void setSubtaskId(int subtaskId);

    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);

    virtual int getResult() const;
    virtual void setResult(int result);

    virtual bool isResult() const;
    virtual void setIsResult(bool isResult);

    virtual bool isGossip() const;
    virtual void setIsGossip(bool isGossip);

    virtual const char * getGossipContent() const;
    virtual void setGossipContent(const char * gossipContent);

    virtual void setArrayArraySize(size_t size);
    virtual size_t getArrayArraySize() const;
    virtual int getArray(size_t k) const;
    virtual void setArray(size_t k, int array);
    virtual void insertArray(size_t k, int array);
    [[deprecated]] void insertArray(int array) {appendArray(array);}
    virtual void appendArray(int array);
    virtual void eraseArray(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ClientMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ClientMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline ClientMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<ClientMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __CLIENTMSG_M_H

